export const APP_ROUTES = {
	LOGIN: '/auth/login',
	FORGOT_PASSWORD: '/auth/forgot-password',

	DASHBOARD: '/admin',
	ROLES: '/admin/roles',
	MEMBERS: '/admin/members',
	CUSTOMERS: '/admin/customers',
	CATEGORIES: '/admin/products/categories',
	PRODUCTS: '/admin/products',
	PRODUCT_DETAILS: '/admin/products/:id',
	REVIEWS: '/admin/reviews',
	REVIEW_DETAILS: '/admin/reviews/:id',
	CART_INSIGHTS: '/admin/insights/cart',
	WISHLIST_INSIGHTS: '/admin/insights/wishlist',
	CUSTOMER_REQUESTS: '/admin/requests',
	ORDERS: '/admin/orders',
	ORDER_DETAILS: '/admin/orders/:id',
	INSTALLMENTS: '/admin/installments',
	INSTALLMENT_DETAILS: '/admin/installments/:id',
};
